<a href="https://colab.research.google.com/github/vivekworldwide/Deep-learning-Notes/blob/main/training_pipeline_using_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [6]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
y_train

543    B
190    M
33     M
83     M
503    M
      ..
189    B
331    B
128    B
77     M
307    B
Name: diagnosis, Length: 455, dtype: object

label encoding

In [8]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [9]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [10]:
X_train_tensor

tensor([[-0.2520,  2.0422, -0.2830,  ..., -0.5406, -0.6891, -1.0810],
        [ 0.0341,  0.8902,  0.1082,  ...,  0.9487,  3.6449,  3.2714],
        [ 1.4642,  1.6714,  1.4905,  ...,  0.9685,  1.2405,  1.5178],
        ...,
        [ 0.2833, -0.6793,  0.3230,  ...,  0.4162, -0.5008, -0.3557],
        [ 1.1187, -0.7353,  1.1730,  ...,  1.4521,  1.3677,  1.4364],
        [-1.4442, -1.1434, -1.4587,  ..., -1.5428,  0.1446, -0.3422]],
       dtype=torch.float64)

In [11]:
X_train_tensor.shape

torch.Size([455, 30])

In [12]:
y_train_tensor.shape

torch.Size([455])

defining model

In [13]:
import torch.nn as nn

class SimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [14]:
learning_rate = 0.1
epochs = 25

In [15]:
#loss fxn
loss_function = nn.BCELoss()

In [16]:
#create model
model = SimpleNN(X_train_tensor.shape[1])

#defining optimizer
optimizer= torch.optim.SGD(model.parameters(), lr = learning_rate)

#define loop
for epoch in range(epochs):

    #forward pass
    y_pred = model(X_train_tensor.float())

    #loss claculation
    loss = loss_function(y_pred, y_train_tensor.float().view(-1,1))

    #clear grad
    optimizer.zero_grad()

    #backword pass
    loss.backward()

    #parameter update
    optimizer.step()


    #print loss in each epoch
    print(f"Epoch: {epoch +1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.621627151966095
Epoch: 2, Loss: 0.48160046339035034
Epoch: 3, Loss: 0.4056658148765564
Epoch: 4, Loss: 0.3575623035430908
Epoch: 5, Loss: 0.32386085391044617
Epoch: 6, Loss: 0.29868608713150024
Epoch: 7, Loss: 0.27901577949523926
Epoch: 8, Loss: 0.2631238102912903
Epoch: 9, Loss: 0.24994859099388123
Epoch: 10, Loss: 0.23879952728748322
Epoch: 11, Loss: 0.2292068749666214
Epoch: 12, Loss: 0.2208394706249237
Epoch: 13, Loss: 0.21345654129981995
Epoch: 14, Loss: 0.20687858760356903
Epoch: 15, Loss: 0.20096881687641144
Epoch: 16, Loss: 0.19562096893787384
Epoch: 17, Loss: 0.19075113534927368
Epoch: 18, Loss: 0.18629200756549835
Epoch: 19, Loss: 0.1821890026330948
Epoch: 20, Loss: 0.17839722335338593
Epoch: 21, Loss: 0.17487940192222595
Epoch: 22, Loss: 0.1716042309999466
Epoch: 23, Loss: 0.16854533553123474
Epoch: 24, Loss: 0.1656801402568817
Epoch: 25, Loss: 0.16298925876617432

In [17]:
#model evalution
with torch.no_grad():
    y_pred = model.forward(X_test_tensor.float())
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor.float().view(-1,1)).float().mean()
    print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.9824561476707458